apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-native-app-dev
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-dev
  template:
    metadata:
      labels:
        app: web-dev
    spec:
      containers:
      - name: web-container
        image: NOOR/cloud-native-app:dev-latest
        ports:
        - containerPort: 80